export default {
  nav: { home: 'الرئيسية', shop: 'المتجر', about: 'عن الموقع', contact: 'اتصل بنا', login: 'تسجيل الدخول', register: 'إنشاء حساب', logout: 'تسجيل الخروج', profile: 'حسابي', dashboard: 'لوحة التحكم', wishlist: 'المفضلة', cart: 'السلة', orders: 'طلباتي', tickets: 'الدعم الفني', settings: 'الإعدادات' },
  home: { heroTitle: 'تسوق بأفضل الأسعار', heroSub: 'اكتشف أحدث المنتجات مع MORISSESHOP', shopNow: 'تسوق الآن', featured: 'منتجات مميزة', latest: 'أحدث المنتجات', discount: 'تخفيض', freeShipping: 'توصيل مجاني', securePayment: 'دفع آمن', support247: 'دعم 24/7' },
  product: { addToCart: 'أضف إلى السلة', addToWishlist: 'أضف إلى المفضلة', removeWishlist: 'إزالة من المفضلة', reviews: 'التقييمات', description: 'الوصف', details: 'التفاصيل', inStock: 'متوفر', outOfStock: 'غير متوفر', price: 'السعر', discount: 'تخفيض', rating: 'التقييم', writeReview: 'اكتب تقييماً', submitReview: 'إرسال التقييم', yourRating: 'تقييمك', yourComment: 'تعليقك', noReviews: 'لا توجد تقييمات بعد' },
  cart: { title: 'سلة التسوق', empty: 'السلة فارغة', checkout: 'إتمام الطلب', total: 'المجموع', subtotal: 'المجموع الفرعي', discount: 'الخصم', coupon: 'كود الخصم', applyCoupon: 'تطبيق', remove: 'حذف', quantity: 'الكمية', continueShopping: 'مواصلة التسوق' },
  order: { title: 'طلباتي', pending: 'قيد الانتظار', confirmed: 'مؤكد', processing: 'قيد المعالجة', shipped: 'تم الشحن', delivered: 'تم التوصيل', cancelled: 'ملغي', noOrders: 'لا توجد طلبات', orderDetails: 'تفاصيل الطلب', shippingAddress: 'عنوان الشحن', paymentMethod: 'طريقة الدفع', cod: 'الدفع عند الاستلام', card: 'بطاقة بنكية', status: 'الحالة' },
  auth: { login: 'تسجيل الدخول', register: 'إنشاء حساب', email: 'البريد الإلكتروني', password: 'كلمة المرور', name: 'الاسم الكامل', phone: 'رقم الهاتف', noAccount: 'ليس لديك حساب؟', haveAccount: 'لديك حساب بالفعل؟', forgotPassword: 'نسيت كلمة المرور؟', loginSuccess: 'تم تسجيل الدخول بنجاح', registerSuccess: 'تم إنشاء الحساب بنجاح' },
  profile: { title: 'حسابي', editProfile: 'تعديل الملف الشخصي', changePassword: 'تغيير كلمة المرور', currentPassword: 'كلمة المرور الحالية', newPassword: 'كلمة المرور الجديدة', save: 'حفظ', saved: 'تم الحفظ', theme: 'المظهر', light: 'فاتح', dark: 'داكن', language: 'اللغة', arabic: 'العربية', french: 'الفرنسية', english: 'الإنجليزية', address: 'العنوان', street: 'الشارع', city: 'المدينة', zip: 'الرمز البريدي' },
  admin: { dashboard: 'لوحة التحكم', products: 'المنتجات', orders: 'الطلبات', users: 'المستخدمين', admins: 'المشرفين', coupons: 'كوبونات الخصم', tickets: 'الدعم الفني', stats: 'الإحصائيات', addProduct: 'إضافة منتج', editProduct: 'تعديل منتج', deleteProduct: 'حذف منتج', addAdmin: 'إضافة مشرف', totalUsers: 'إجمالي المستخدمين', totalProducts: 'إجمالي المنتجات', totalOrders: 'إجمالي الطلبات', totalRevenue: 'إجمالي الإيرادات', permissions: 'الصلاحيات', manageProducts: 'إدارة المنتجات', manageOrders: 'إدارة الطلبات', manageUsers: 'إدارة المستخدمين', manageAdmins: 'إدارة المشرفين', manageCoupons: 'إدارة الكوبونات', manageTickets: 'إدارة الدعم' },
  ticket: { title: 'الدعم الفني', newTicket: 'تذكرة جديدة', subject: 'الموضوع', message: 'الرسالة', priority: 'الأولوية', low: 'منخفضة', medium: 'متوسطة', high: 'عالية', urgent: 'عاجلة', open: 'مفتوحة', inProgress: 'قيد المعالجة', resolved: 'تم الحل', closed: 'مغلقة', respond: 'رد', noTickets: 'لا توجد تذاكر' },
  common: { loading: 'جار التحميل...', error: 'خطأ', success: 'تم بنجاح', save: 'حفظ', cancel: 'إلغاء', delete: 'حذف', edit: 'تعديل', add: 'إضافة', search: 'بحث', filter: 'تصفية', sort: 'ترتيب', noData: 'لا توجد بيانات', back: 'رجوع', next: 'التالي', prev: 'السابق', all: 'الكل', yes: 'نعم', no: 'لا', confirm: 'تأكيد', close: 'إغلاق' },
  coupon: { title: 'كوبونات الخصم', code: 'الكود', type: 'النوع', value: 'القيمة', percentage: 'نسبة مئوية', fixed: 'قيمة ثابتة', minOrder: 'أدنى طلب', maxUses: 'أقصى استخدام', used: 'مستخدم', expiresAt: 'ينتهي في', isActive: 'مفعل', addCoupon: 'إضافة كوبون', noCoupons: 'لا توجد كوبونات' },
  whatsapp: 'تواصل معنا عبر واتساب',
  footer: { rights: 'جميع الحقوق محفوظة', description: 'متجر إلكتروني مغربي يقدم أفضل المنتجات بأفضل الأسعار', quickLinks: 'روابط سريعة', followUs: 'تابعنا' }
};
