export default {
  nav: { home: 'Home', shop: 'Shop', about: 'About', contact: 'Contact', login: 'Login', register: 'Register', logout: 'Logout', profile: 'My Profile', dashboard: 'Dashboard', wishlist: 'Wishlist', cart: 'Cart', orders: 'My Orders', tickets: 'Support', settings: 'Settings' },
  home: { heroTitle: 'Shop at Best Prices', heroSub: 'Discover the latest products with MORISSESHOP', shopNow: 'Shop Now', featured: 'Featured Products', latest: 'Latest Products', discount: 'Discount', freeShipping: 'Free Shipping', securePayment: 'Secure Payment', support247: '24/7 Support' },
  product: { addToCart: 'Add to Cart', addToWishlist: 'Add to Wishlist', removeWishlist: 'Remove from Wishlist', reviews: 'Reviews', description: 'Description', details: 'Details', inStock: 'In Stock', outOfStock: 'Out of Stock', price: 'Price', discount: 'Discount', rating: 'Rating', writeReview: 'Write a Review', submitReview: 'Submit Review', yourRating: 'Your Rating', yourComment: 'Your Comment', noReviews: 'No reviews yet' },
  cart: { title: 'Shopping Cart', empty: 'Cart is empty', checkout: 'Checkout', total: 'Total', subtotal: 'Subtotal', discount: 'Discount', coupon: 'Coupon Code', applyCoupon: 'Apply', remove: 'Remove', quantity: 'Quantity', continueShopping: 'Continue Shopping' },
  order: { title: 'My Orders', pending: 'Pending', confirmed: 'Confirmed', processing: 'Processing', shipped: 'Shipped', delivered: 'Delivered', cancelled: 'Cancelled', noOrders: 'No orders', orderDetails: 'Order Details', shippingAddress: 'Shipping Address', paymentMethod: 'Payment Method', cod: 'Cash on Delivery', card: 'Bank Card', status: 'Status' },
  auth: { login: 'Login', register: 'Register', email: 'Email', password: 'Password', name: 'Full Name', phone: 'Phone', noAccount: "Don't have an account?", haveAccount: 'Already have an account?', forgotPassword: 'Forgot password?', loginSuccess: 'Login successful', registerSuccess: 'Account created successfully' },
  profile: { title: 'My Profile', editProfile: 'Edit Profile', changePassword: 'Change Password', currentPassword: 'Current Password', newPassword: 'New Password', save: 'Save', saved: 'Saved', theme: 'Theme', light: 'Light', dark: 'Dark', language: 'Language', arabic: 'Arabic', french: 'French', english: 'English', address: 'Address', street: 'Street', city: 'City', zip: 'ZIP Code' },
  admin: { dashboard: 'Dashboard', products: 'Products', orders: 'Orders', users: 'Users', admins: 'Admins', coupons: 'Coupons', tickets: 'Support Tickets', stats: 'Statistics', addProduct: 'Add Product', editProduct: 'Edit Product', deleteProduct: 'Delete Product', addAdmin: 'Add Admin', totalUsers: 'Total Users', totalProducts: 'Total Products', totalOrders: 'Total Orders', totalRevenue: 'Total Revenue', permissions: 'Permissions', manageProducts: 'Manage Products', manageOrders: 'Manage Orders', manageUsers: 'Manage Users', manageAdmins: 'Manage Admins', manageCoupons: 'Manage Coupons', manageTickets: 'Manage Support' },
  ticket: { title: 'Support Tickets', newTicket: 'New Ticket', subject: 'Subject', message: 'Message', priority: 'Priority', low: 'Low', medium: 'Medium', high: 'High', urgent: 'Urgent', open: 'Open', inProgress: 'In Progress', resolved: 'Resolved', closed: 'Closed', respond: 'Respond', noTickets: 'No tickets' },
  common: { loading: 'Loading...', error: 'Error', success: 'Success', save: 'Save', cancel: 'Cancel', delete: 'Delete', edit: 'Edit', add: 'Add', search: 'Search', filter: 'Filter', sort: 'Sort', noData: 'No data found', back: 'Back', next: 'Next', prev: 'Previous', all: 'All', yes: 'Yes', no: 'No', confirm: 'Confirm', close: 'Close' },
  coupon: { title: 'Coupons', code: 'Code', type: 'Type', value: 'Value', percentage: 'Percentage', fixed: 'Fixed Amount', minOrder: 'Min Order', maxUses: 'Max Uses', used: 'Used', expiresAt: 'Expires At', isActive: 'Active', addCoupon: 'Add Coupon', noCoupons: 'No coupons' },
  whatsapp: 'Contact us on WhatsApp',
  footer: { rights: 'All rights reserved', description: 'Moroccan online store offering the best products at the best prices', quickLinks: 'Quick Links', followUs: 'Follow Us' }
};
