export default {
  nav: { home: 'Accueil', shop: 'Boutique', about: 'À propos', contact: 'Contact', login: 'Connexion', register: 'S\'inscrire', logout: 'Déconnexion', profile: 'Mon Profil', dashboard: 'Tableau de bord', wishlist: 'Favoris', cart: 'Panier', orders: 'Mes commandes', tickets: 'Support', settings: 'Paramètres' },
  home: { heroTitle: 'Aux Meilleurs Prix', heroSub: 'Découvrez les derniers produits avec MORISSESHOP', shopNow: 'Acheter maintenant', featured: 'Produits en vedette', latest: 'Nouveaux produits', discount: 'Réduction', freeShipping: 'Livraison gratuite', securePayment: 'Paiement sécurisé', support247: 'Support 24/7' },
  product: { addToCart: 'Ajouter au panier', addToWishlist: 'Ajouter aux favoris', removeWishlist: 'Retirer des favoris', reviews: 'Avis', description: 'Description', details: 'Détails', inStock: 'En stock', outOfStock: 'Rupture de stock', price: 'Prix', discount: 'Réduction', rating: 'Note', writeReview: 'Écrire un avis', submitReview: 'Soumettre', yourRating: 'Votre note', yourComment: 'Votre commentaire', noReviews: 'Aucun avis pour le moment' },
  cart: { title: 'Panier', empty: 'Panier vide', checkout: 'Commander', total: 'Total', subtotal: 'Sous-total', discount: 'Réduction', coupon: 'Code promo', applyCoupon: 'Appliquer', remove: 'Supprimer', quantity: 'Quantité', continueShopping: 'Continuer' },
  order: { title: 'Mes commandes', pending: 'En attente', confirmed: 'Confirmée', processing: 'En cours', shipped: 'Expédiée', delivered: 'Livrée', cancelled: 'Annulée', noOrders: 'Aucune commande', orderDetails: 'Détails de la commande', shippingAddress: 'Adresse de livraison', paymentMethod: 'Méthode de paiement', cod: 'Paiement à la livraison', card: 'Carte bancaire', status: 'Statut' },
  auth: { login: 'Connexion', register: 'Inscription', email: 'Email', password: 'Mot de passe', name: 'Nom complet', phone: 'Téléphone', noAccount: 'Pas de compte ?', haveAccount: 'Déjà un compte ?', forgotPassword: 'Mot de passe oublié ?', loginSuccess: 'Connecté avec succès', registerSuccess: 'Compte créé avec succès' },
  profile: { title: 'Mon Profil', editProfile: 'Modifier le profil', changePassword: 'Changer mot de passe', currentPassword: 'Mot de passe actuel', newPassword: 'Nouveau mot de passe', save: 'Enregistrer', saved: 'Enregistré', theme: 'Thème', light: 'Clair', dark: 'Sombre', language: 'Langue', arabic: 'Arabe', french: 'Français', english: 'Anglais', address: 'Adresse', street: 'Rue', city: 'Ville', zip: 'Code postal' },
  admin: { dashboard: 'Tableau de bord', products: 'Produits', orders: 'Commandes', users: 'Utilisateurs', admins: 'Administrateurs', coupons: 'Coupons', tickets: 'Support', stats: 'Statistiques', addProduct: 'Ajouter produit', editProduct: 'Modifier produit', deleteProduct: 'Supprimer produit', addAdmin: 'Ajouter admin', totalUsers: 'Total utilisateurs', totalProducts: 'Total produits', totalOrders: 'Total commandes', totalRevenue: 'Revenu total', permissions: 'Permissions', manageProducts: 'Gérer produits', manageOrders: 'Gérer commandes', manageUsers: 'Gérer utilisateurs', manageAdmins: 'Gérer admins', manageCoupons: 'Gérer coupons', manageTickets: 'Gérer support' },
  ticket: { title: 'Support', newTicket: 'Nouveau ticket', subject: 'Sujet', message: 'Message', priority: 'Priorité', low: 'Basse', medium: 'Moyenne', high: 'Haute', urgent: 'Urgente', open: 'Ouvert', inProgress: 'En cours', resolved: 'Résolu', closed: 'Fermé', respond: 'Répondre', noTickets: 'Aucun ticket' },
  common: { loading: 'Chargement...', error: 'Erreur', success: 'Succès', save: 'Enregistrer', cancel: 'Annuler', delete: 'Supprimer', edit: 'Modifier', add: 'Ajouter', search: 'Rechercher', filter: 'Filtrer', sort: 'Trier', noData: 'Aucune donnée', back: 'Retour', next: 'Suivant', prev: 'Précédent', all: 'Tout', yes: 'Oui', no: 'Non', confirm: 'Confirmer', close: 'Fermer' },
  coupon: { title: 'Coupons', code: 'Code', type: 'Type', value: 'Valeur', percentage: 'Pourcentage', fixed: 'Montant fixe', minOrder: 'Commande min', maxUses: 'Utilisations max', used: 'Utilisé', expiresAt: 'Expire le', isActive: 'Actif', addCoupon: 'Ajouter coupon', noCoupons: 'Aucun coupon' },
  whatsapp: 'Contactez-nous sur WhatsApp',
  footer: { rights: 'Tous droits réservés', description: 'Boutique marocaine en ligne offrant les meilleurs produits aux meilleurs prix', quickLinks: 'Liens rapides', followUs: 'Suivez-nous' }
};
